sudo: false
language: python

python:
  - "2.7"
  # - "3.3" - not supported by travis anymore
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install -r requirements.txt
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"

script:
  - py.test

branches:
    only:
        - master
